# Configuration of the CI pipeline
name: 'Amazon S3 Bucket'
canonical: 'infra-amazon-s3'
status: 'public'
description: 'This infrastructure will deploy a S3 bucket on AWS.'
keywords:
  - 's3'
  - 'aws'
  - 'iam'
  - 'terraform'
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/infra-amazon-s3/master/icon.png'
type: 'infra'
technologies:
  - technology: Amazon s3
    version: n/a
  - technology: terraform
    version: n/a
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/s3.yml'
    variables:
      path: 'pipeline/variables.sample.yml'

  # Configuration of ansible for provisionning
  ansible: {}

  # Configuration of terraform to setup the infrastructure
  terraform:
    s3:
      path: 'terraform/s3.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/s3.tf'
