version: "2"
name: jamestestagain123
canonical: jamestestagain123
author: James Fontaine Herrera
status: private
description: james test again
image: ""
keywords:
- sf31455
- provider:aws
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      jamestestagain123:
        destination: ($ project $)/default/terraform/($ environment $)/jamestestagain123.tf
        path: default/terraform/jamestestagain123.tf.sample
